

#Makefile variable definitions
CC = /usr/bin/gcc
LD = /usr/bin/gcc
CFLAGS =
LDFLAGS =
LIB = pthread -lrt
RM = /bin/rm -f
#
#Variables for the file being compiled
###########################
#NAME = 
###########################
#
#OBJS = $(NAME).o
#PROG = $(NAME)
#SRC = $(NAME).c

all: nt_lab2_sol1_final nt_lab2_sol2_final nt_lab2_sol3_final

nt_lab2_sol1_final:
	$(CC) $(CFLAGS) -o nt_lab2_sol1_final nt_lab2_sol1_final.c -$(LIB)

nt_lab2_sol2_final:
	$(CC) $(CFLAGS) -o nt_lab2_sol2_final nt_lab2_sol2_final.c -$(LIB)

nt_lab2_sol3_final:
	$(CC) $(CFLAGS) -o nt_lab2_sol3_final nt_lab2_sol3_final.c -$(LIB)

